# prometheus-values.yaml

global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'vault'
    static_configs:
      - targets: ['vault.vault-deployment.svc.cluster.local:8200']

alerting:
  alertmanagers:
    - static_configs:
      - targets: ['alertmanager.monitoring.svc.cluster.local:9093']

alertmanager:
  service:
    enabled: true
    ports:
      - name: web
        port: 9093
        targetPort: 9093
